### ISSUE TITLE
webpack-plugin repo

### ISSUE THREAD

**Issue by joshperry** [loft-sh/jspolicy#117]
Noticed that the github.com/loft-sh/jspolicy-webpack-plugin repo is not public.
I was able to read the code in the package, but I thought this might be an oversight.

**Comment by FabianKramm** [comment]
@joshperry good catch, we made that repo public!

**Comment by alexandradragodan** [comment]
Thanks for flagging this, @joshperry !

Closing the issue for now then.

**Comment by agilgur5** [comment]
> Noticed that the github.com/loft-sh/jspolicy-webpack-plugin repo is not public.



> @joshperry good catch, we made that repo public!

Quick link for reference: https://github.com/loft-sh/jspolicy-webpack-plugin
