### ISSUE TITLE
FEATURE REQUEST - jspolicy as a generic sidecar injector

### ISSUE THREAD

**Issue by infa-ddeore** [loft-sh/jspolicy#23]
will it be possible to use jsplicy as a sidecar injector?

use case:
my cluster has 3 different types of sidecar injector pods running. Instead of running all these 3 injectors, if `jspolicy` can mutate the deployment based on annotation then i would stop all these 3 injector pods and use jspolicy for adminssion controls as well as sidecar injector

there may be different set of templates that jspolicy can refer to inject sidecar

this would reduce running multiple injector/ controller pods

**Comment by FabianKramm** [comment]
@infa-ddeore thanks for creating this issue! Sure thats possible, we already have an example how to inject sidecar containers with jspolicy: https://github.com/loft-sh/jspolicy/blob/main/examples/by-use-case/inject-sidecar-container.yaml

**Comment by infa-ddeore** [comment]
wonderful!
