### ISSUE TITLE
imagePullSecrets support in helm

### ISSUE THREAD

**Issue by infa-ddeore** [loft-sh/jspolicy#25]
helm chart doesn't have imagePullSecret option so the images would come from docker hub and may get ratelimited by docker

**Comment by FabianKramm** [comment]
@infa-ddeore thanks a lot for creating this issue! Yes that makes sense, we'll add an option!

**Comment by infa-ddeore** [comment]
thanks @FabianKramm for the response, it also need to provide option to update image, currently it is hardcoded

**Comment by FabianKramm** [comment]
@infa-ddeore yes that makes sense, we'll add that as well

**Comment by infa-ddeore** [comment]
my bad, [image variable](https://github.com/loft-sh/jspolicy/blob/main/chart/templates/deployment.yaml#L38-L40) is present already, only `imagePullSecrets` is needed

**Comment by infa-ddeore** [comment]
@FabianKramm i created PR #28 , could you merge if that looks okay?
