### ISSUE TITLE
reduce docker image size and use non-root user

### ISSUE THREAD

**Issue by infa-ddeore** [loft-sh/jspolicy#32]
`loftsh/jspolicy` image is around 1.2G, also the jspolicy process runs as root user which would flag security concerns

1. can the image size be reduced
2. i think root user is used to listen on 80 and 443 port but this can be higher ports (>1024) and expose them on 80/443 via k8s service so root user isnt required

**Comment by FabianKramm** [comment]
@infa-ddeore thanks for creating this issue! Makes sense, we'll try to add this

**Comment by FabianKramm** [comment]
@infa-ddeore we decreased image size by a significant margin as well as default jsPolicy running as non root in v0.2.0-beta.3
