### ISSUE TITLE
name should be a domain with at least three segments separated by dots

### ISSUE THREAD

**Issue by protosam** [loft-sh/jspolicy#4]
This doesn't really make sense. Why does it matter what the name format is?

If there's no reason for this, can I make a pull to remove this restriction?

```text
jspolicy-testing$ cat <<EOF | kubectl apply -f -
apiVersion: policy.jspolicy.com/v1beta1
kind: JsPolicy
metadata:
  name: "deny-default"
spec:
  operations: ["CREATE", "UPDATE"]
  resources: ["pods"]
  scope: Namespaced
  javascript: |
    if (request.object.metadata.namespace === "default") {
      deny("Creation of resources within this namespace is not allowed!");
    }
EOF
Error from server (Forbidden): error when creating "STDIN": admission webhook "jspolicy.jspolicy.com" denied the request: metadata.name: Invalid value: "deny-default": should be a domain with at least three segments separated by dots
```

**Comment by FabianKramm** [comment]
@protosam thanks for creating this issue! The reason for this is that we convert a JsPolicy object into a ValidatingWebhookConfiguration which requires the name to be "a domain with at least three segments separated by dots" and we reuse some parts of the original validation code for webhooks. 

To be honest, I'm not exactly sure why Kubernetes introduced this requirement, however I believe we could also allow policies that does not fit that naming convention and append a `jspolicy.com` for the webhook automatically.

**Comment by protosam** [comment]
[I see](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/) what you mean here and I also can't find a clear explanation for it. My best guess it's to enforce some consistency like they do with CRDs.

Perhaps the rule be like this?
* if metadata.name matches *.*.*, use that for the ValidatingWebhookConfiguration
* else append `.policy.jspolicy.com`

I figure this give flexibility in being compatible with all the examples and documentation that already exists.

Looking at the source, I'm assuming this logic would need to live in [pkg/controllers/jspolicy.go](https://github.com/loft-sh/jspolicy/blob/main/pkg/controllers/jspolicy.go).

I can implement this change and make a pull request if this is a reasonable change.

**Comment by FabianKramm** [comment]
@protosam Yes sounds like a good idea, I think appending `.jspolicy.com` is already enough. Would be great if you make a PR, the following things you probably need to consider:
- You need to change the name generation in 
https://github.com/loft-sh/jspolicy/blob/d98643fe3363250657f7175a3177d38ca9024632/pkg/controllers/jspolicy.go#L449
as well as 
https://github.com/loft-sh/jspolicy/blob/d98643fe3363250657f7175a3177d38ca9024632/pkg/controllers/jspolicy.go#L550
- The second thing you need to do is to adjust the validation part of js policy to allow names that do not fit this pattern. You can change this at https://github.com/loft-sh/jspolicy/blob/d98643fe3363250657f7175a3177d38ca9024632/pkg/webhook/validation/generic.go#L152

Hope that helps and many thanks that you want to contribute to js policy!

**Comment by protosam** [comment]
Finally got around to writing code for this and I've actually had a change of opinion on making the PR for this. 

When looking at how replicasets and jobs build on top of pods; using those resources have a requisite of knowledge of what a pod is to make them work. While it's not immediately obvious that a ValidatingWebhookConfiguration is made and I don't know why that component requires an FQDN, someone somewhere thought it did. 

I think I'm just going this as-is with the assumption that users should understand underlying objects that get created.
